context("hash tables")

test_that("hash tables work", {
  e <- ht_new()
  expect_equal(ht_list(e), character(0))
  expect_false(ht_exists(e, "a"))
  expect_false(ht_exists(e, "b"))
  ht_add(e, c("a", "b"))
  expect_true(ht_exists(e, "a"))
  expect_true(ht_exists(e, "b"))
  hd_del(e, "a")
  expect_false(ht_exists(e, "a"))
  expect_true(ht_exists(e, "b"))
  expect_equal(ht_list(e), "b")
})
