# library(testthat); library(devtools); load_all()
context("full-build")
source("utils.R")

test_that("scratch build with contained envir.", {
  dclean()
  config = dbug()
  expect_error(session())
  expect_true(length(status()) == 0)
  expect_equal(config$cache$list(), character(0))
  testrun(config)
  expect_true(is.numeric(readd(final)))
  expect_true(length(config$cache$list()) > 2)
  expect_false(any(c("f", "final") %in% ls()))
  expect_true(is.list(session()))
  expect_true(all(session()$target %in% config$plan$target))
  
  # changed nothing
  testrun(config)
  nobuild(config)
  
  # take this opportunity to test clean() and prune()
  all = c("'input.rds'", "'intermediatefile.rds'", "a",
    "b", "c", "combined", "f", "final", "g", "h", "i",
    "j", "myinput", "nextone", "readRDS", "saveRDS",
    "yourinput")
  expect_equal(config$cache$list(), all)
  expect_true(file.exists("intermediatefile.rds"))
  expect_true(file.exists("input.rds"))
  expect_true(file.exists(cachepath))
  clean(x = "final")
  expect_equal(config$cache$list(), setdiff(all, "final"))
  expect_true(file.exists("intermediatefile.rds"))
  prune(config$plan[config$plan$target == "myinput",])
  expect_false(file.exists("intermediatefile.rds"))
  expect_true(file.exists("input.rds"))
  expect_equal(config$cache$list(), 
    c("'input.rds'", "myinput", "readRDS"))
  clean()
  expect_equal(config$cache$list(), character(0))
  expect_false(file.exists("intermediatefile.rds"))
  expect_true(file.exists("input.rds"))
  expect_true(file.exists(cachepath))
  expect_equal(config$cache$list("filemtime"), character(0))
  clean(destroy = TRUE)
  expect_false(file.exists(cachepath))
  dclean()
})

test_that("calling environment is unaffected in scratch build.", {
  dclean()
  config = dbug()
  for(x in ls(config$envir)) assign(x, config$envir[[x]], environment())
  if("obj" %in% ls()) rm(obj)
  obj = ls()
  expect_equal(config$cache$list(), character(0))
  make(config$plan, verbose = FALSE)
  expect_equal(sort(c(obj, "obj")), ls())
  expect_true(length(config$cache$list()) > 0)
  dclean()
  expect_false(file.exists("input.rds"))
})
