drake_context("hash tables")

test_with_dir("hash tables work", {
  e <- ht_new()
  expect_equal(ht_list(e), character(0))
  expect_false(ht_exists(e, "a"))
  expect_false(ht_exists(e, "b"))
  ht_add(e, c("a", "b"))
  expect_true(ht_exists(e, "a"))
  expect_true(ht_exists(e, "b"))
  ht_del(e, "a")
  expect_false(ht_exists(e, "a"))
  expect_true(ht_exists(e, "b"))
  expect_equal(ht_list(e), "b")
  f <- ht_clone(e)
  ht_add(f, "xyz")
  expect_false(ht_exists(e, "xyz"))
  expect_true(ht_exists(f, "xyz"))
  ht_del(f, "xyz")
  expect_false(ht_exists(f, "xyz"))
  g <- ht_new(letters)
  expect_true(all(ht_exists(g, letters)))
})
