# library(testthat); library(devtools); load_all()
context("importfile")
source("utils.R")

test_that("responses to imported file", {
  dclean()
  args = dbug()
  expect_output(check(plan = args$plan, envir = args$envir))
  expect_error(check(plan = args$plan[-1,], envir = args$envir))
  expect_silent(check(plan = args$plan[c(-1, -6),], envir = args$envir))
  run(args$plan, envir = args$envir, verbose = F)
  expect_true(nrow(status()) > 0)
  run(args$plan, envir = args$envir, verbose = F)
  nobuild(args)
  unlink("input.rds")
  expect_error(check(plan = args$plan, envir = args$envir))
  saveRDS(1:10, "input.rds")
  run(args$plan, envir = args$envir, verbose = F)
  nobuild(args)
  final0 = readd(final)
  saveRDS(2:10, "input.rds")
  run(args$plan, envir = args$envir, verbose = F)
  expect_equal(justbuilt(), c("'intermediatefile.rds'",
    "combined", "final", "myinput", "nextone"))
  expect_false(length(final0) == length(readd(final)))
  dclean()
})
