```{r}
library(drake)
library(magrittr)
```

```{r}
mtcars_link <- 
  "https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html"
iris_link <- 
  "https://archive.ics.uci.edu/ml/datasets/iris"
iris3_link <- 
  "https://www.rdocumentation.org/packages/datasets/versions/3.6.1/topics/iris"

plan <- drake::drake_plan(
  mtc = target(
    mtcars,
    link = !!mtcars_link
  ),
  ir = target(
    iris,
    link = !!iris_link
  ),
  ir3 = target(
    modify_iris3(iris3, number),
    transform = map(number = !!c(1:3), .tag_in = cluster_id ),
    link = !!iris3_link
  ),
  trace = TRUE
)
```
```{r}
config <- drake::drake_config(plan)
```
```{r}
unique_stems <- plan$cluster_id %>% unique()

graph_info <- drake_graph_info(
  config,
  targets_only = TRUE,
  group = "cluster_id",
  clusters = unique_stems,
  show_output_files = FALSE,
  build_times = "none",
  hover = FALSE,
  on_select_col = "link"
)
```

# Perform the default action on select

```{r}
drake::render_drake_graph(graph_info = graph_info, on_select = TRUE)
```
# Perform no action on select

Since `on_select = NULL` was given

```{r}
drake::vis_drake_graph(config, clusters = unique_stems, hover = FALSE, on_select_col = "link", on_select = NULL)
```

# Perform the default action on select

This time calling from `vis_drake_graph()`

```{r}
drake::vis_drake_graph(config, clusters = unique_stems, group = "cluster_id",
                       hover = FALSE, on_select_col = "link", on_select = TRUE)
```

# Display an alert on select

```{r}
alert_behaviour <- function(){
  js <- "
  function(props) {
    alert('selected node with on_select_col: \\r\\n' +
            this.body.data.nodes.get(props.nodes[0]).on_select_col);
  }"
}

drake::vis_drake_graph(config, clusters = unique_stems, group = "cluster_id",
                       hover = FALSE, on_select_col = "link",
                       on_select = alert_behaviour())
```

