#' @title Function \code{clean}
#' @description Cleans up all work done by \code{\link{run}()}. 
#' Your working directory (\code{\link{getwd}()}) must be the 
#' root directory of your drake project.
#' WARNING:
#' This deletes ALL work done with \code{\link{run}()}, which includes 
#' file targets as well as the entire drake cache. Only use \code{clean()}
#' if you're sure you won't lose anything important.
#' @seealso \code{\link{prune}}, \code{\link{run}}, 
#' @export
#' @param destroy logical, whether to totally remove the drake cache. 
#' If \code{destroy} is \code{FALSE}, only the targets 
#' from \code{run}()
#' are removed. If \code{TRUE}, the whole cache is removed, including
#' session metadata, etc.
clean = function(destroy = FALSE){
  if(!file.exists(cachepath)) return(invisible())
  cache = storr_rds(cachepath, mangle_key = TRUE)
  files = cached() %>% Filter(f = is_file) 
  remove_target_files(files)
  if(destroy) unlink(cachepath, recursive = TRUE)
  else uncache(cached())
  invisible()
}

#' @title Function \code{prune}
#' @description Removes any cached targets not listed in 
#' \code{plan$target}, including file targets and their 
#' cached fingerprints. 
#' Your working directory (\code{\link{getwd}()}) must be the
#' root directory of your project.
#' WARNING: this removes objects and files generated by drake.
#' Only do this if you're sure you won't lose any important work.
#' @seealso \code{\link{clean}}, \code{\link{run}}
#' @export
#' @param plan workflow plan data frame, as generated by 
#' \code{\link{plan}}. 
prune = function(plan, targets = plan$targets, envir = parent.frame()){
  force(envir)
  args = setup(plan = plan, targets = targets, envir = envir, 
               verbose = FALSE, jobs = 1, prework = character(0),
               command = character(0), args = character(0))
  check_args(args)
  keep = args$order
  remove = setdiff(cached(), keep)
  files = Filter(remove, f = is_file)
  remove_target_files(files)
  uncache(remove)
  invisible()
}

remove_target_files = Vectorize(function(file){
  if(!is_imported(file, path = getwd(), search = FALSE)) 
    unlink(unquote(file), recursive = TRUE)
}, "file")
