#' @title Turn a `drake` workflow plan data frame
#'   into a plain R script file.
#' @export
#' @seealso [drake_plan()], [make()], [code_to_plan()],
#'   [plan_to_notebook()]
#' @description `code_to_plan()`, [plan_to_code()], and
#'   [plan_to_notebook()] together illustrate the relationships
#'   between `drake` plans, R scripts, and R Markdown documents.
#'   In the file generated by `plan_to_code()`, every target/command pair
#'   becomes a chunk of code.
#'   Targets are arranged in topological order
#'   so dependencies are available before their downstream targets.
#'   Please note:
#'   1. You are still responsible for loading your project's
#'     packages, imported functions, etc.
#'   2. Triggers disappear.
#' @param plan workflow plan data frame. See [drake_plan()]
#'   for details.
#' @param con a file path or connection to write to.
#' @examples
#' plan <- drake_plan(
#'   raw_data = read_excel(file_in("raw_data.xlsx")),
#'   data = raw_data %>%
#'     mutate(Species = fct_inorder(Species)) %>%
#'     select(-X__1),
#'   hist = create_plot(data),
#'   fit = lm(Sepal.Width ~ Petal.Width + Species, data),
#'   strings_in_dots = "literals"
#' )
#' file <- tempfile()
#' # Turn the plan into an R script a the given file path.
#' plan_to_code(plan, file)
#' # Here is what the script looks like.
#' cat(readLines(file), sep = "\n")
#' # Convert back to a drake plan.
#' code_to_plan(file)
plan_to_code <- function(plan, con = stdout()){
  writeLines(text = plan_to_text(plan), con = con)
}

#' @title Turn a `drake` workflow plan data frame
#'   into an R notebook,
#' @export
#' @seealso [drake_plan()], [make()], [code_to_plan()],
#'   [plan_to_code()]
#' @description `code_to_plan()`, [plan_to_code()], and
#'   [plan_to_notebook()] together illustrate the relationships
#'   between `drake` plans, R scripts, and R Markdown documents.
#'   In the file generated by `plan_to_code()`, every target/command pair
#'   becomes a chunk of code.
#'   Targets are arranged in topological order
#'   so dependencies are available before their downstream targets.
#'   Please note:
#'   1. You are still responsible for loading your project's
#'     packages, imported functions, etc.
#'   2. Triggers disappear.
#' @inheritParams plan_to_code
#' @examples
#' plan <- drake_plan(
#'   raw_data = read_excel(file_in("raw_data.xlsx")),
#'   data = raw_data %>%
#'     mutate(Species = fct_inorder(Species)) %>%
#'     select(-X__1),
#'   hist = create_plot(data),
#'   fit = lm(Sepal.Width ~ Petal.Width + Species, data),
#'   strings_in_dots = "literals"
#' )
#' file <- tempfile()
#' # Turn the plan into an R notebook a the given file path.
#' plan_to_notebook(plan, file)
#' # Here is what the script looks like.
#' cat(readLines(file), sep = "\n")
#' # Convert back to a drake plan.
#' code_to_plan(file)
plan_to_notebook <- function(plan, con){
  c(
    "---",
    "title: \"My Notebook\"",
    "output: html_notebook",
    "---",
    "",
    "```{r my_code}",
    plan_to_text(plan),
    "```"
  ) %>%
    writeLines(con = con)
}

plan_to_text <- function(plan){
  . <- NULL
  order <- drake_config(
    plan,
    envir = new.env(parent = emptyenv()),
    cache = storr::storr_environment(),
    verbose = FALSE
  )$graph %>%
    igraph::topo_sort() %>%
    .$name %>%
    intersect(y = plan$target) %>%
    match(table = plan$target)
  plan <- plan[order, ]
  if (!is.character(plan$command)){
    plan$command <- purrr::map_chr(plan$command, rlang::expr_text)
  }
  text <- paste(plan$target, "<-", plan$command)
  if (requireNamespace("styler")){
    text <- styler::style_text(text)
  }
  text
}
